[2024-03-23T06:34:12.183+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: source_to_gcs.upload_file_gcs manual__2024-03-23T06:20:25.835237+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
