[2024-03-22T14:28:55.686+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T14:28:43.976419+00:00 [queued]>
[2024-03-22T14:28:55.699+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T14:28:43.976419+00:00 [queued]>
[2024-03-22T14:28:55.700+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-22T14:28:55.722+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_check_result> on 2024-03-22 14:28:43.976419+00:00
[2024-03-22T14:28:55.733+0000] {standard_task_runner.py:60} INFO - Started process 804 to run task
[2024-03-22T14:28:55.741+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'source_to_gcs', 'get_check_result', 'manual__2024-03-22T14:28:43.976419+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/sourcetobucket.py', '--cfg-path', '/tmp/tmp99kuhpnl']
[2024-03-22T14:28:55.745+0000] {standard_task_runner.py:88} INFO - Job 175: Subtask get_check_result
[2024-03-22T14:28:55.823+0000] {task_command.py:423} INFO - Running <TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T14:28:43.976419+00:00 [running]> on host ceb99a37e23c
[2024-03-22T14:28:55.945+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='source_to_gcs' AIRFLOW_CTX_TASK_ID='get_check_result' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T14:28:43.976419+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-22T14:28:43.976419+00:00'
[2024-03-22T14:28:55.951+0000] {sql.py:785} INFO - Executing SQL check: SELECT COUNT(1) from used_car_analysis_dataset.used_car_price LIMIT 1
[2024-03-22T14:28:55.964+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-22T14:28:55.968+0000] {base.py:83} INFO - Using connection ID 'gcp_***_conn' for task execution.
[2024-03-22T14:28:56.045+0000] {sql.py:457} INFO - Running statement: SELECT COUNT(1) from used_car_analysis_dataset.used_car_price LIMIT 1, parameters: None
[2024-03-22T14:28:56.048+0000] {bigquery.py:1613} INFO - Inserting job ***_1711117736047127_fabb2f9006d5ccbe668044ee8692b8ed
[2024-03-22T14:28:57.112+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:407: AirflowProviderDeprecationWarning: Call to deprecated method _make_common_data_structure. (The `_make_serializable` method is deprecated and support will be removed in a future version of the common.sql provider. Please update the DbApiHook's provider to a version based on common.sql >= 1.9.1.)
  result = self._make_common_data_structure(handler(cur))

[2024-03-22T14:28:57.114+0000] {sql.py:788} INFO - Record: [558799]
[2024-03-22T14:28:57.114+0000] {sql.py:796} INFO - Success.
[2024-03-22T14:28:57.115+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sourcetobucket.py", line 79, in run_bigquery_check
    result = task_instance.xcom_pull(task_ids="check_table_is_present")
AttributeError: 'NoneType' object has no attribute 'xcom_pull'
[2024-03-22T14:28:57.127+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=source_to_gcs, task_id=get_check_result, execution_date=20240322T142843, start_date=20240322T142855, end_date=20240322T142857
[2024-03-22T14:28:57.148+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 175 for task get_check_result ('NoneType' object has no attribute 'xcom_pull'; 804)
[2024-03-22T14:28:57.200+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-22T14:28:57.227+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
